baseURL = "https://autonomy.githuka.com"
title = "Fundi Willy's Autonomous Vehicles Workshop"
themesDir = "/home/wilfred/githuka_sites/autonomy_website/autonomy/themes/"
theme = "m10c"
paginate = 10

[params]
  author = "Wilfred Githuka"
  description = "A low level technical view of autonomous vehicles > wilfred.gachugi[-at-]gmail.com"
  [[params.social]]
    name = "github"
    url = "https://github.com/wilfredgithuka"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/wilfredgithuka"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
